name: CMake
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_project:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-10 g++-10 cmake build-essential
        shell: bash
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_CXX_COMPILER=g++-10
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{github.workspace}}/build
