name: CMake
on:
  pull_request:
  push:
    branches:
      - main
jobs:
run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build tools and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10 cmake build-essential qt5-default qdbus
      shell: bash
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build
        -DCMAKE_CXX_COMPILER=g++-10
        -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Deb package
      run: >
      cd build/
      cpack
    # Publish deb
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: sharing_service-0.1.1-Linux.deb
        path: {{github.workspace}}/build/sharing_service-0.1.1-Linux.deb